### ISSUE TITLE
After creating a new offer an exception happens, but seems to have no influence 

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#53] opened 2015-07-24 13:24 UTC
07-24 15:23:34.776    8759-8759/neeedo.imimaprx.htw.de.neeedo E/ActivityThread﹕ Activity neeedo.imimaprx.htw.de.neeedo.LocationChooserActivity has leaked IntentReceiver android.widget.AbsSeekBar$2@16ea09c2 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity neeedo.imimaprx.htw.de.neeedo.LocationChooserActivity has leaked IntentReceiver android.widget.AbsSeekBar$2@16ea09c2 that was originally registered here. Are you missing a call to unregisterReceiver()?
            at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:968)
            at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:769)
            at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:2016)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1996)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1990)
            at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:503)
            at android.widget.AbsSeekBar.registerReceiver(AbsSeekBar.java:1603)
            at android.widget.AbsSeekBar.<init>(AbsSeekBar.java:209)
            at android.widget.SeekBar.<init>(SeekBar.java:87)
            at android.widget.SeekBar.<init>(SeekBar.java:83)
            at android.widget.SeekBar.<init>(SeekBar.java:79)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:614)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at neeedo.imimaprx.htw.de.neeedo.LocationChooserActivity.onCreate(LocationChooserActivity.java:57)
            at android.app.Activity.performCreate(Activity.java:6374)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by TIIUNDER** [comment] 2015-07-24 14:25
It seems hard to reproduce. There seems to be a problem with location chooser. But It's still possible to create new offer, so no big problem.

**Comment by TIIUNDER** [comment] 2015-07-24 14:26
@stephanlindauer You can decide if we want to fix this, you can also set it to wontfix if you want

**Comment by stephanlindauer** [comment] 2015-07-24 15:21
i think i already fixed this by reworking the saveinstance stuff. would close this ticket. if the problem comes up again we can open it again.

**Closed as completed by stephanlindauer** 2015-07-24 15:21 UTC
Labels: bug
