### ISSUE TITLE
After registration the single views have wrong not-logged-in state

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#82] opened 2015-07-27 16:39 UTC

**Comment by TIIUNDER** [comment] 2015-07-27 16:46
Strange, how do you get an own offer? The own offers hide that button

**Comment by stephanlindauer** [comment] 2015-07-27 16:47
"List my Offers" :)

**Comment by stephanlindauer** [comment] 2015-07-27 17:12
also happens when i send a message to migration user

**Comment by stephanlindauer** [comment] 2015-07-27 17:12
07-27 19:10:41.712    6728-6751/neeedo.imimaprx.htw.de.neeedo E/GetMessagesAsyncTask﹕ 404 Not Found
    org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.message.GetMessagesAsyncTask.doInBackground(GetMessagesAsyncTask.java:64)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-27 19:10:42.584    6728-6757/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ GET request for "https://api.neeedo.com/conversations/?read=false" resulted in 404 (Not Found); invoking error handler
07-27 19:10:42.586    6728-6757/neeedo.imimaprx.htw.de.neeedo E/GetMessagesByUserIdAndReadStateAsyncTask﹕ 404 Not Found
    org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.message.GetMessagesByUserIdAndReadStateAsyncTask.doInBackground(GetMessagesByUserIdAndReadStateAsyncTask.java:57)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-27 19:10:46.491    6728-6728/neeedo.imimaprx.htw.de.neeedo D/AndroidRuntime﹕ Shutting down VM
07-27 19:10:46.498    6728-6728/neeedo.imimaprx.htw.de.neeedo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: neeedo.imimaprx.htw.de.neeedo, PID: 6728
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
            at neeedo.imimaprx.htw.de.neeedo.fragments.adapters.MessageListArrayAdapter.getView(MessageListArrayAdapter.java:52)
            at android.widget.AbsListView.obtainView(AbsListView.java:2347)
            at android.widget.ListView.makeAndAddView(ListView.java:1864)
            at android.widget.ListView.fillUp(ListView.java:732)
            at android.widget.ListView.layoutChildren(ListView.java:1677)
            at android.widget.AbsListView.onLayout(AbsListView.java:2151)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$Met
07-27 19:11:12.636    6728-6761/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ GET request for "https://api.neeedo.com/conversations/?read=false" resulted in 404 (Not Found); invoking error handler
07-27 19:11:12.640    6728-6761/neeedo.imimaprx.htw.de.neeedo E/GetMessagesByUserIdAndReadStateAsyncTask﹕ 404 Not Found
    org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.message.GetMessagesByUserIdAndReadStateAsyncTask.doInBackground(GetMessagesByUserIdAndReadStateAsyncTask.java:57)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by TIIUNDER** [comment] 2015-07-27 17:21
@stephanlindauer I was not able to reproduce this issue. Please check the latest commit if the message button is still visible.

**Comment by stephanlindauer** [comment] 2015-07-27 17:35
![screenshot_2015-07-27-19-34-12](https://cloud.githubusercontent.com/assets/1323145/8913007/9a4f9a10-3496-11e5-9976-74d8071a40ae.png)

**Comment by stephanlindauer** [comment] 2015-07-27 17:35
Nope. Completely reinstalled an registered a New user.

**Comment by TIIUNDER** [comment] 2015-07-27 17:37
Are you sure this is your own offer? Also the fav-button should not be there and there should be edit and delete buttons

**Comment by stephanlindauer** [comment] 2015-07-27 17:51
yapp

**Comment by GammaG** [comment] 2015-07-27 18:10
that looks like the public view, because edit and delete are missing. So somehow the owership check must go wrong

**Comment by GammaG** [comment] 2015-07-27 18:28
Ah I managed to get this error too. Just works if you create a new user and without closing the app create a new offer.

**Comment by TIIUNDER** [comment] 2015-07-27 18:32
I'm not able to reproduce this anywhere. Neither in emulators or on other test devices. 
@GammaG can you check, if there is a way to double check the ownership of an offer?

**Comment by GammaG** [comment] 2015-07-27 18:36
After registration userid in ActiveUser still is "" somehow.

**Comment by GammaG** [comment] 2015-07-27 18:38
guess I found it in PostCreateUpdateUserAsyncTask 2 lines were in the wrong order.

**Comment by TIIUNDER** [comment] 2015-07-27 18:50
Ah, ok, now I was able to reproduce. After registering this happens, after login it works as expected.

**Comment by GammaG** [comment] 2015-07-27 18:54
found it. Problem was user registration model does not return the password again, due that password in active user was always "". Because of that evey userCredentialsAvailable() request will deliver false and because of that the owercheck didn't even start. I temporarly save now the password and set it in the return model. After that I fill active user. 

should work now 
@TIIUNDER login uses an other service, there the password comes from the textfield due that it exists.

**Closed as completed** 2015-07-27 18:54 UTC
Labels: bug
